site_name: Plural Self-Respect
site_url: https://pluralrespect.github.io/selfrespect
site_description: A crash course on the prickles of systemhood for systems - a more personal expansion of Plural Respect.
#copyright: CC-BY-SA 4.0 International

nav:
  - Foreword: index.md
  - Slang / Casual Concepts: slang.md
  - Prickles in Fuzztivehood: fuzztivehood.md
  - Prickles in Quantity: quantity.md
  - Repression and Reclamation: reclamation.md
  - Rapport and Re-Meet: rapport.md
  - Cycles of Null Exploration: exploration.md
  - Novelty and Flanderisation: flanderization.md
  - Microcosmic Sexuality: sexuality.md
  - Challenges in Communication: communication.md
  - Prickles in Hyper-Individualism: individualism.md

theme: windmill

extra_css:
    - css/theme-adjustments.css

extra:
  version: 1.0.0
  logo: img/custom-journey-flag.png
  article_nav_top: false